### ISSUE TITLE
Include the CHANGELOG for the release

### ISSUE THREAD

**Issue by olleolleolle** [rubygems/bundler-site#1233]
This Issue is about making it harder to break a link in the BUG_TRIAGE section.

https://github.com/rubygems/rubygems/pull/7041#issuecomment-1752825512

Suggestion: include the rubygems/rubygems repo's Bundler CHANGELOG.md for the version we build for, and let it be called "CHANGELOG.md" in all of bunder-site.

(This is a duplicate of https://github.com/rubygems/bundler-site/issues/846.)

**Comment by deivid-rodriguez** [comment]
I think we'd need to add one more entry for changelog.md below this line?

https://github.com/rubygems/bundler-site/blob/4a4256b040aeac936a202d9f221ef429928983b5/lib/tasks/vendor_files.rake#L67

**Comment by tnir** [comment]
Thanks @olleolleolle !
