### ISSUE TITLE
rake build: Stop requiring non-existent git branches

### ISSUE THREAD

**Issue by olleolleolle** [rubygems/bundler-site#1307]
`rake build` is a long list of tasks in one.

It used to build content for old versions, which had long-running Git branches in this repository. Then, we moved this repository, and made a cut-off at some point. In any case, the rake task now fails on "I can't checkout that remote branch".

So: update the task to not expect those old non-existent branches

**Comment by olleolleolle** [comment]
The VERSIONS.each in lib/tasks/man_generator/man.rake asks "is this a deprecated branch?", and enters logic that tries to use a branch like 1-13-stable, for example. Those branches are gone.

**Comment by olleolleolle** [comment]
I guess an idea would be "take the generated content that exists, and keep it, for those versions".

**Comment by deivid-rodriguez** [comment]
@olleolleolle This is actually working fine for me and the implementation looks also correct. When looping through all versions, the task uses the [old repo](https://github.com/rubygems/bundler/) (cloned at `vendor/bundler`) for old branches (where those branches do exist), and it uses the new repo for more recent branches. See

https://github.com/rubygems/bundler-site/blob/84ed917d5e25f3066f37cfb591f7d881cb2e79c4/lib/tasks/man_generator/man.rake#L6-L14

**Comment by olleolleolle** [comment]
@deivid-rodriguez Wonderful news.

I guess I need to study how to run the manual-building commands.

I started here, https://github.com/rubygems/bundler-site?tab=readme-ov-file#basic-middleman-commands and had that error.

**Comment by deivid-rodriguez** [comment]
Can you still reproduce the error?

**Comment by olleolleolle** [comment]
@deivid-rodriguez This is the output now,

```
olle.jonsson@Olles-Laptop bundler-site % bundle exec rake man
git fetch
git fetch
remote: Enumerating objects: 434, done.
remote: Counting objects: 100% (237/237), done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 84 (delta 60), reused 15 (delta 6), pack-reused 0
Unpacking objects: 100% (84/84), 18.66 KiB | 347.00 KiB/s, done.
From https://github.com/rubygems/rubygems
 + 7c29a6e7a...5f2033b0d deivid-rodriguez/truffleruby -> origin/deivid-rodriguez/truffleruby  (forced update)
   ed8b5fee2..894b72463  master                       -> origin/master
mkdir -p source/v1.12/man
git reset --hard HEAD
HEAD is now at 84ed917d chore(deps): Bump rexml from 3.3.1 to 3.3.2 (#1370)
git checkout origin/1-12-stable
error: pathspec 'origin/1-12-stable' did not match any file(s) known to git
rake aborted!
Command failed with status (1): [git checkout origin/1-12-stable]
lib/tasks/man_generator/man.rake:21:in `block (3 levels) in <top (required)>'
lib/tasks/man_generator/man.rake:19:in `chdir'
lib/tasks/man_generator/man.rake:19:in `block (2 levels) in <top (required)>'
lib/tasks/man_generator/man.rake:3:in `each'
lib/tasks/man_generator/man.rake:3:in `block in <top (required)>'
/Users/olle.jonsson/.rbenv/versions/3.3.1/bin/bundle:25:in `load'
/Users/olle.jonsson/.rbenv/versions/3.3.1/bin/bundle:25:in `<main>'
Tasks: TOP => man
(See full trace by running task with --trace)
```

**Comment by deivid-rodriguez** [comment]
Can you try removing the vendored copy of the old repo (`rm -rf vendor/bundler`) and run the task again?

**Comment by olleolleolle** [comment]
@deivid-rodriguez THAT made it work, this is super, closing this issue!
