### ISSUE TITLE
Explain complete behavior of `bundle update --source gem`

### ISSUE THREAD

**Issue by robinboening** [rubygems/bundler-site#165]
@neoeno did a great job inspecting the `--source` option and explained it in this issue https://github.com/bundler/bundler/issues/3759.

Wether this functionality will be renamed in the future or not, this knowledge should be shared on the website.

Site on which the `--source` option is mentioned: http://bundler.io/v1.10/bundle_update.html

Source file to be updated: https://github.com/bundler/bundler-site/blob/master/source/v1.10/bundle_update.haml

@indirect do you agree?

**Comment by indirect** [comment]
Yup, that would be fantastic. :+1:

**Comment by kruczjak** [comment]
After #218 the file changed. It's converted from https://github.com/bundler/bundler/blob/master/man/bundle-update.ronn.

**Comment by deivid-rodriguez** [comment]
Yes, the `--conservative` flag works properly these days to update conservatively, and it should be used instead. Thanks for updating this old ticket!
