### ISSUE TITLE
locale support

### ISSUE THREAD

**Issue by coilysiren** [rubygems/bundler-site#211]
- [ ] #563
- [ ] #564

**Comment by kruczjak** [comment]
Maybe we could use e.g. https://lingohub.com/ for translating to different languages. 
This one is free for Open Source projects but needs approval from their "sales team".

**Comment by kruczjak** [comment]
I've created simple widget for changing locales here: #221

**Comment by tnir** [comment]
Closing as this has been stale for 6 years and in https://github.com/rubygems/bundler-site/pull/221#issuecomment-621460672, this issue was broken down to #563 and #564 by @duckinator.

- #563
- #564
