### ISSUE TITLE
Rework sponsor acknowledgements

### ISSUE THREAD

**Issue by indirect** [rubygems/bundler-site#219]
I'd like to add a small section (footer? maybe just the bottom of the homepage?) thanking our current sponsors: Ruby Together for funding development, Ruby Central for servers, and Librato for metrics. Linking to each of their sites would be nice, too.

**Comment by tnir** [comment]
@indirect Can you close this now as Bundler project is only supported by Ruby Central via Ruby Together?

**Comment by tnir** [comment]
@kruczjak looks absent from the team now...

**Comment by indirect** [comment]
👍🏻
