### ISSUE TITLE
Known bundler plugins

### ISSUE THREAD

**Issue by bronzdoc** [rubygems/bundler-site#505]
"This would be a page on the Bundler website, with a rake task we can run to query rubygems and update the list of plugins and link to their gem pages."

See: https://github.com/rubygems/rubygems/issues/3376

**Comment by olleolleolle** [comment]
I'll try to do something about this tonight.

**Comment by tnir** [comment]
Hi @olleolleolle, do you have any plan to complete this? You just stated the problem in #505 as below but I am not able to find the page on the Web site:

> See #505 - there is no Known Plugins page in the site.

**Comment by olleolleolle** [comment]
@tnir oh,  thanks for asking, I won't be doing anything about this, now.

**Comment by tnir** [comment]
Okay, @olleolleolle. Remove you from assignees and push it to https://github.com/rubygems/bundler-site/contribute.
