### ISSUE TITLE
Intermittent CI failure

### ISSUE THREAD

**Issue by duckinator** [rubygems/bundler-site#519]
So, [this happened](https://github.com/rubygems/bundler-site/runs/631081948):

```
Run NO_CONTRACTS=true bundle exec middleman build
/home/runner/work/bundler-site/bundler-site/vendor/bundle/gems/ffi-1.11.1/lib/ffi/library.rb:112: [BUG] Illegal instruction at 0x00007f2352dcbcf0
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0042 p:---- s:0223 e:000222 CFUNC  :open
[...]
```

Seems related to https://github.com/sass/sassc-ruby/issues/183. I'll look into this tomorrow if nobody else gets to it first.

**Comment by duckinator** [comment]
Apparently you can just [re-run all the jobs over and over and eventually it works](https://twitter.com/duckinator/status/1255926595258388481).

**Comment by simi** [comment]
:thinking: I think this could be temporarily solved by removing bundler cache on CI. Should we at least try that?

**Comment by duckinator** [comment]
@simi it's worth a shot, yeah. Slower CI is better than intermittently breaking CI. :slightly_smiling_face:

**Comment by simi** [comment]
@duckinator I have created 2 PRs trying to fix this problem:

- https://github.com/rubygems/bundler-site/pull/521 (Update sassc to 2.3.0.)
- https://github.com/rubygems/bundler-site/pull/520 (Force reinstall sassc on CI)

I suggest to merge #521 first since it should fix the problem (per https://github.com/sass/sassc-ruby/pull/158). If we will still see CI fails, we can go with #520 temporarily for now and inspect again.

**Comment by duckinator** [comment]
@simi merged #521. Guess we'll have to wait until a few more things get merged into master to see how it goes?

**Comment by simi** [comment]
Yes. We can help a little by restarting master CI few times. I do not have permission to do that. But if anyone can do that, it would be helpful.

**Comment by duckinator** [comment]
I don't see a way to restart CI when it succeeds (only when it fails), nor a way to start a new build from scratch. So not sure of a good way to test it. :woman_shrugging:

**Comment by duckinator** [comment]
It seems like @simi's PRs fixed this, so I'm closing this. Can always re-open or open a new issue if it starts happening again. :+1:
