### ISSUE TITLE
Fix SSL-related documentation on bundler.io

### ISSUE THREAD

**Issue by MartinKoerner** [rubygems/bundler-site#540]
This is an issue about the bundler.io documentation.
I can also prepare a pull request, if you hint the location of the source code of the website.

### Describe the problem as clearly as you can

The documentation of the recently changed Certificate is outdated:
https://bundler.io/v2.0/guides/rubygems_tls_ssl_troubleshooting_guide.html#automated-ssl-check (Chapter "Updating CA certificates")

1. The link "GlobalSignRootCA.pem" should refer to "https://github.com/rubygems/rubygems/blob/master/lib/rubygems/ssl_certs/rubygems.org/GlobalSignRootCA_R3.pem"
2. In "Step 3: Copy new trust certificate" it should be made clear to put the certificate in directory "...rubygems/ssl_certs/rubygems.org"

**Comment by olleolleolle** [comment]
The new URL with the same properties as the existing one would be: 

`https://raw.githubusercontent.com/rubygems/rubygems/master/lib/rubygems/ssl_certs/rubygems.org/GlobalSignRootCA_R3.pem`

**Comment by olleolleolle** [comment]
@MartinKoerner I made the URL change, and it's merged. If you want to clarify docs, go ahead!

**Comment by olleolleolle** [comment]
@MartinKoerner If you want to offer a Pull Request about clarifying, go ahead!

**Comment by MartinKoerner** [comment]
Sorry for the delay, I added #574

**Comment by olleolleolle** [comment]
@MartinKoerner Thank you! :hearts: :yellow_heart: :green_heart: :blue_heart: :purple_heart:
