### ISSUE TITLE
I have a problem with Thermox 

### ISSUE THREAD

**Issue by mosab3482** [rubygems/bundler-site#543]
Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on freenode

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * Unstable: pkg install unstable-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues

$ gem update --system
The program gem is not installed. Install it by executing:
 pkg install ruby
$ pkg install ruby
Checking availability of current mirror: ok
Ign:1 https://termux.mentality.rip/termux-packages-24 stable InRelease
Hit:2 https://termux.mentality.rip/termux-packages-24 stable Release
Ign:4 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:5 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Get:6 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:6 https://dl.bintray.com/grimler/game-packages-24 games Release
Get:7 https://dl.bintray.com/grimler/science-packages-24 science Release [6191 B]
Hit:7 https://dl.bintray.com/grimler/science-packages-24 science Release
Reading package lists... Done
Building dependency tree
Reading state information... Done
25 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  binutils clang gdbm glib libffi libllvm
  libyaml make ndk-sysroot pkg-config
The following NEW packages will be installed:
  binutils clang gdbm glib libffi libllvm
  libyaml make ndk-sysroot pkg-config ruby
0 upgraded, 11 newly installed, 0 to remove and 25 not upgraded.
Need to get 47.5 MB of archives.
After this operation, 236 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://termux.mentality.rip/termux-packages-24 stable/main arm binutils arm 2.35.1-1 [2160 kB]
Get:2 https://termux.mentality.rip/termux-packages-24 stable/main arm ndk-sysroot arm 21d [1643 kB]
Get:3 https://termux.mentality.rip/termux-packages-24 stable/main arm libffi arm 3.3-2 [31.1 kB]
Get:4 https://termux.mentality.rip/termux-packages-24 stable/main arm libllvm arm 11.0.0-1 [19.1 MB]
Get:5 https://termux.mentality.rip/termux-packages-24 stable/main arm clang arm 11.0.0-1 [18.9 MB]
Err:5 https://termux.mentality.rip/termux-packages-24 stable/main arm clang arm 11.0.0-1
  OpenSSL SSL_read: Software caused connection abort, errno 103
Err:6 https://termux.mentality.rip/termux-packages-24 stable/main arm gdbm arm 1.18.1-3
  FailReason: ConnectionRefused
Err:7 https://termux.mentality.rip/termux-packages-24 stable/main arm glib arm 2.66.1
  FailReason: ConnectionRefused
Err:8 https://termux.mentality.rip/termux-packages-24 stable/main arm libyaml arm 0.2.5-4
  FailReason: ConnectionRefused
Err:9 https://termux.mentality.rip/termux-packages-24 stable/main arm make arm 4.3-1
  FailReason: ConnectionRefused
Err:10 https://termux.mentality.rip/termux-packages-24 stable/main arm pkg-config arm 0.29.2
  FailReason: ConnectionRefused
Err:11 https://termux.mentality.rip/termux-packages-24 stable/main arm ruby arm 2.7.2-2
  FailReason: ConnectionRefused
Fetched 23.0 MB in 4min 46s (80.2 kB/s)
E: Failed to fetch https://termux.mentality.rip/termux-packages-24/arm/clang_11.0.0-1_arm.deb  OpenSSL SSL_read: Software caused connection abort, errno 103
E: Failed to fetch https://termux.mentality.rip/termux-packages-24/arm/gdbm_1.18.1-3_arm.deb  FailReason: ConnectionRefused
E: Failed to fetch https://termux.mentality.rip/termux-packages-24/arm/glib_2.66.1_arm.deb  FailReason: ConnectionRefused
E: Failed to fetch https://termux.mentality.rip/termux-packages-24/arm/libyaml_0.2.5-4_arm.deb  FailReason: ConnectionRefused
E: Failed to fetch https://termux.mentality.rip/termux-packages-24/arm/make_4.3-1_arm.deb  FailReason: ConnectionRefused
E: Failed to fetch https://termux.mentality.rip/termux-packages-24/arm/pkg-config_0.29.2_arm.deb  FailReason: ConnectionRefused
E: Failed to fetch https://termux.mentality.rip/termux-packages-24/arm/ruby_2.7.2-2_arm.deb  FailReason: ConnectionRefused
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
$ pkg install ruby
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  binutils clang gdbm glib libffi libllvm
  libyaml make ndk-sysroot pkg-config
The following NEW packages will be installed:
  binutils clang gdbm glib libffi libllvm
  libyaml make ndk-sysroot pkg-config ruby
0 upgraded, 11 newly installed, 0 to remove and 25 not upgraded.
Need to get 24.5 MB/47.5 MB of archives.
After this operation, 236 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://termux.mentality.rip/termux-packages-24 stable/main arm clang arm 11.0.0-1 [18.9 MB]
Get:2 https://termux.mentality.rip/termux-packages-24 stable/main arm gdbm arm 1.18.1-3 [103 kB]
Get:3 https://termux.mentality.rip/termux-packages-24 stable/main arm glib arm 2.66.1 [1089 kB]
Get:4 https://termux.mentality.rip/termux-packages-24 stable/main arm libyaml arm 0.2.5-4 [45.0 kB]
Get:5 https://termux.mentality.rip/termux-packages-24 stable/main arm make arm 4.3-1 [222 kB]
Get:6 https://termux.mentality.rip/termux-packages-24 stable/main arm pkg-config arm 0.29.2 [25.6 kB]
Get:7 https://termux.mentality.rip/termux-packages-24 stable/main arm ruby arm 2.7.2-2 [4200 kB]
Fetched 24.5 MB in 3min 33s (115 kB/s)
Selecting previously unselected package binutils.
(Reading database ... 3748 files and directories currently installed.)
Preparing to unpack .../00-binutils_2.35.1-1_arm.deb ...
Unpacking binutils (2.35.1-1) ...
Selecting previously unselected package ndk-sysroot.
Preparing to unpack .../01-ndk-sysroot_21d_arm.deb ...
Unpacking ndk-sysroot (21d) ...
Selecting previously unselected package libffi.
Preparing to unpack .../02-libffi_3.3-2_arm.deb ...
Unpacking libffi (3.3-2) ...
Selecting previously unselected package libllvm.
Preparing to unpack .../03-libllvm_11.0.0-1_arm.deb ...
Unpacking libllvm (11.0.0-1) ...
Selecting previously unselected package clang.
Preparing to unpack .../04-clang_11.0.0-1_arm.deb ...
Unpacking clang (11.0.0-1) ...
Selecting previously unselected package gdbm.
Preparing to unpack .../05-gdbm_1.18.1-3_arm.deb ...
Unpacking gdbm (1.18.1-3) ...
Selecting previously unselected package glib.
Preparing to unpack .../06-glib_2.66.1_arm.deb ...
Unpacking glib (2.66.1) ...
Selecting previously unselected package libyaml.
Preparing to unpack .../07-libyaml_0.2.5-4_arm.deb ...
Unpacking libyaml (0.2.5-4) ...
Selecting previously unselected package make.
Preparing to unpack .../08-make_4.3-1_arm.deb ...
Unpacking make (4.3-1) ...
Selecting previously unselected package pkg-config.
Preparing to unpack .../09-pkg-config_0.29.2_arm.deb ...
Unpacking pkg-config (0.29.2) ...
Selecting previously unselected package ruby.
Preparing to unpack .../10-ruby_2.7.2-2_arm.deb ...
Unpacking ruby (2.7.2-2) ...
Setting up gdbm (1.18.1-3) ...
Setting up ndk-sysroot (21d) ...
Setting up binutils (2.35.1-1) ...
Setting up libffi (3.3-2) ...
Setting up libyaml (0.2.5-4) ...
Setting up ruby (2.7.2-2) ...
Setting up make (4.3-1) ...
Setting up libllvm (11.0.0-1) ...
Setting up glib (2.66.1) ...
Setting up clang (11.0.0-1) ...
Setting up pkg-config (0.29.2) ...
$ ls
kali-binds  kali-fs  kali.sh  start-kali.sh
$ git clone https://github.com/rubygems/
The program git is not installed. Install it by executing:
 pkg install git
$ git clone https://github.com/rubygems/
The program git is not installed. Install it by executing:
 pkg install git
$ pkg install git
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  git
0 upgraded, 1 newly installed, 0 to remove and 25 not upgraded.
Need to get 2842 kB of archives.
After this operation, 10.7 MB of additional disk space will be used.
Get:1 https://termux.mentality.rip/termux-packages-24 stable/main arm git arm 2.29.2 [2842 kB]
Fetched 2842 kB in 33s (84.4 kB/s)
Selecting previously unselected package git.
(Reading database ... 10590 files and directories currently installed.)
Preparing to unpack .../archives/git_2.29.2_arm.deb ...
Unpacking git (2.29.2) ...
Setting up git (2.29.2) ...
$ git clone https://github.com/rubygems/
Cloning into 'rubygems'...
remote: Not Found
fatal: repository 'https://github.com/rubygems/' not found
$ ls
kali-binds  kali-fs  kali.sh  start-kali.sh
$ git clone https://github.com/rubygems/bundler-site.git
Cloning into 'bundler-site'...
remote: Enumerating objects: 146, done.
remote: Counting objects: 100% (146/146), done.
remote: Compressing objects: 100% (105/105), done
Receiving objects:   2% (144/7163), 92.00 KiB | 11Receiving objects:   2% (185/7163), 92.00 KiB | 11Receiving objects:   3% (215/7163), 92.00 KiB | 11Receiving objects:   4% (287/7163), 148.00 KiB | 1Receiving objects:   5% (359/7163), 148.00 KiB | 1Receiving objects:   5% (407/7163), 220.00 KiB | 8Receiving objects:   6% (430/7163), 220.00 KiB | 8Receiving objects:   6% (436/7163), 228.00 KiB | 6Receiving objects:   7% (502/7163), 228.00 KiB | 6Receiving objects:   8% (574/7163), 228.00 KiB | 6Receiving objects:   9% (645/7163), 228.00 KiB | 6Receiving objects:  10% (717/7163), 228.00 KiB | 6Receiving objects:  11% (788/7163), 228.00 KiB | 6Receiving objects:  12% (860/7163), 228.00 KiB | 6Receiving objects:  13% (932/7163), 228.00 KiB | 6Receiving objects:  13% (1001/7163), 228.00 KiB | Receiving objects:  14% (1003/7163), 228.00 KiB | Receiving objects:  15% (1075/7163), 356.00 KiB | Receiving objects:  16% (1147/7163), 356.00 KiB | Receiving objects:  17% (1218/7163), 356.00 KiB | Receiving objects:  18% (1290/7163), 356.00 KiB | Receiving objects:  19% (1361/7163), 420.00 KiB | Receiving objects:  19% (1426/7163), 420.00 KiB | Receiving objects:  20% (1433/7163), 420.00 KiB | Receiving objects:  20% (1484/7163), 540.00 KiB | Receiving objects:  20% (1485/7163), 708.00 KiB | Receiving objects:  20% (1493/7163), 916.00 KiB | Receiving objects:  20% (1494/7163), 964.00 KiB | Receiving objects:  20% (1496/7163), 1.03 MiB | 10Receiving objects:  21% (1505/7163), 1.03 MiB | 10Receiving objects:  21% (1509/7163), 1.17 MiB | 99Receiving objects:  21% (1518/7163), 1.25 MiB | 10Receiving objects:  21% (1522/7163), 1.39 MiB | 10Receiving objects:  21% (1526/7163), 1.52 MiB | 11Receiving objects:  22% (1576/7163), 1.52 MiB | 11Receiving objects:  23% (1648/7163), 1.57 MiB | 12Receiving objects:  23% (1651/7163), 1.61 MiB | 11Receiving objects:  24% (1720/7163), 1.61 MiB | 11Receiving objects:  25% (1791/7163), 1.70 MiB | 11Receiving objects:  25% (1806/7163), 1.70 MiB | 11Receiving objects:  26% (1863/7163), 1.70 MiB | 11Receiving objects:  27% (1935/7163), 1.77 MiB | 12Receiving objects:  27% (1995/7163), 1.83 MiB | 11Receiving objects:  28% (2006/7163), 1.83 MiB | 11Receiving objects:  29% (2078/7163), 1.83 MiB | 11Receiving objects:  30% (2149/7163), 1.83 MiB | 11Receiving objects:  31% (2221/7163), 1.92 MiB | 11Receiving objects:  32% (2293/7163), 1.92 MiB | 11Receiving objects:  32% (2342/7163), 1.92 MiB | 11Receiving objects:  33% (2364/7163), 1.92 MiB | 11Receiving objects:  33% (2394/7163), 2.04 MiB | 11Receiving objects:  33% (2399/7163), 2.25 MiB | 12Receiving objects:  33% (2402/7163), 2.28 MiB | 84Receiving objects:  34% (2436/7163), 2.28 MiB | 84Receiving objects:  35% (2508/7163), 2.28 MiB | 84Receiving objects:  36% (2579/7163), 2.28 MiB | 84Receiving objects:  36% (2603/7163), 2.28 MiB | 84Receiving objects:  36% (2604/7163), 2.48 MiB | 94Receiving objects:  37% (2651/7163), 2.48 MiB | 94Receiving objects:  38% (2722/7163), 2.48 MiB | 94Receiving objects:  39% (2794/7163), 2.48 MiB | 94Receiving objects:  40% (2866/7163), 2.48 MiB | 94Receiving objects:  41% (2937/7163), 2.48 MiB | 94Receiving objects:  42% (3009/7163), 2.56 MiB | 92Receiving objects:  42% (3060/7163), 2.56 MiB | 92Receiving objects:  43% (3081/7163), 2.56 MiB | 92Receiving objects:  44% (3152/7163), 2.62 MiB | 91Receiving objects:  45% (3224/7163), 2.62 MiB | 91Receiving objects:  46% (3295/7163), 2.62 MiB | 91Receiving objects:  47% (3367/7163), 2.62 MiB | 91Receiving objects:  48% (3439/7163), 2.62 MiB | 91Receiving objects:  49% (3510/7163), 2.62 MiB | 91Receiving objects:  50% (3582/7163), 2.70 MiB | 93Receiving objects:  50% (3651/7163), 2.70 MiB | 93Receiving objects:  50% (3652/7163), 2.84 MiB | 89Receiving objects:  51% (3654/7163), 2.84 MiB | 89Receiving objects:  51% (3655/7163), 2.94 MiB | 95Receiving objects:  51% (3655/7163), 3.06 MiB | 12Receiving objects:  51% (3656/7163), 3.21 MiB | 11Receiving objects:  51% (3657/7163), 3.28 MiB | 11Receiving objects:  51% (3657/7163), 3.42 MiB | 12Receiving objects:  51% (3657/7163), 3.50 MiB | 12Receiving objects:  51% (3657/7163), 3.64 MiB | 11Receiving objects:  51% (3658/7163), 3.77 MiB | 11Receiving objects:  51% (3658/7163), 3.86 MiB | 11Receiving objects:  51% (3658/7163), 3.99 MiB | 11Receiving objects:  51% (3658/7163), 4.07 MiB | 11Receiving objects:  51% (3658/7163), 4.22 MiB | 11Receiving objects:  51% (3661/7163), 4.30 MiB | 11Receiving objects:  51% (3664/7163), 4.37 MiB | 11Receiving objects:  51% (3667/7163), 4.55 MiB | 11Receiving objects:  51% (3668/7163), 4.68 MiB | 12Receiving objects:  51% (3670/7163), 4.80 MiB | 11Receiving objects:  51% (3671/7163), 4.89 MiB | 12Receiving objects:  52% (3725/7163), 4.89 MiB | 12Receiving objects:  53% (3797/7163), 4.96 MiB | 12Receiving objects:  54% (3869/7163), 4.96 MiB | 12Receiving objects:  55% (3940/7163), 4.96 MiB | 12Receiving objects:  55% (3955/7163), 5.02 MiB | 12Receiving objects:  55% (3955/7163), 5.14 MiB | 11Receiving objects:  56% (4012/7163), 5.18 MiB | 11Receiving objects:  57% (4083/7163), 5.18 MiB | 11Receiving objects:  57% (4113/7163), 5.25 MiB | 11Receiving objects:  57% (4144/7163), 5.33 MiB | 11Receiving objects:  58% (4155/7163), 5.33 MiB | 11Receiving objects:  58% (4157/7163), 5.36 MiB | 63Receiving objects:  59% (4227/7163), 5.36 MiB | 63Receiving objects:  59% (4230/7163), 5.36 MiB | 63Receiving objects:  59% (4231/7163), 6.08 MiB | 11Receiving objects:  59% (4232/7163), 6.13 MiB | 11Receiving objects:  59% (4233/7163), 6.32 MiB | 12Receiving objects:  59% (4233/7163), 6.35 MiB | 11Receiving objects:  59% (4233/7163), 6.39 MiB | 79Receiving objects:  59% (4234/7163), 6.39 MiB | 79Receiving objects:  59% (4235/7163), 7.07 MiB | 11Receiving objects:  59% (4235/7163), 7.14 MiB | 11Receiving objects:  59% (4235/7163), 7.29 MiB | 11Receiving objects:  59% (4235/7163), 7.32 MiB | 82Receiving objects:  59% (4235/7163), 7.38 MiB | 86Receiving objects:  59% (4236/7163), 7.44 MiB | 13Receiving objects:  59% (4244/7163), 7.96 MiB | 11Receiving objects:  59% (4286/7163), 8.08 MiB | 11Receiving objects:  59% (4287/7163), 8.22 MiB | 12Receiving objects:  59% (4288/7163), 8.25 MiB | 11Receiving objects:  59% (4289/7163), 8.36 MiB | 11Receiving objects:  60% (4298/7163), 8.36 MiB | 11Receiving objects:  61% (4370/7163), 8.36 MiB | 11Receiving objects:  61% (4375/7163), 8.91 MiB | 11Receiving objects:  61% (4375/7163), 8.97 MiB | 11Receiving objects:  61% (4375/7163), 9.14 MiB | 11Receiving objects:  61% (4375/7163), 9.18 MiB | 79Receiving objects:  62% (4442/7163), 9.18 MiB | 79Receiving objects:  63% (4513/7163), 9.18 MiB | 79Receiving objects:  64% (4585/7163), 9.18 MiB | 79Receiving objects:  64% (4606/7163), 9.71 MiB | 16Receiving objects:  65% (4656/7163), 9.71 MiB | 16Receiving objects:  66% (4728/7163), 9.71 MiB | 16Receiving objects:  67% (4800/7163), 9.71 MiB | 16Receiving objects:  68% (4871/7163), 9.77 MiB | 16Receiving objects:  69% (4943/7163), 9.77 MiB | 16Receiving objects:  70% (5015/7163), 9.77 MiB | 16Receiving objects:  70% (5021/7163), 9.77 MiB | 16Receiving objects:  71% (5086/7163), 9.77 MiB | 16Receiving objects:  72% (5158/7163), 9.82 MiB | 16Receiving objects:  73% (5229/7163), 9.82 MiB | 16Receiving objects:  73% (5279/7163), 9.86 MiB | 11Receiving objects:  74% (5301/7163), 9.94 MiB | 11Receiving objects:  75% (5373/7163), 9.94 MiB | 11Receiving objects:  76% (5444/7163), 10.00 MiB | 1Receiving objects:  76% (5453/7163), 10.00 MiB | 1Receiving objects:  77% (5516/7163), 10.00 MiB | 1Receiving objects:  78% (5588/7163), 10.00 MiB | 1Receiving objects:  79% (5659/7163), 10.00 MiB | 1Receiving objects:  80% (5731/7163), 10.08 MiB | 1Receiving objects:  81% (5803/7163), 10.08 MiB | 1Receiving objects:  82% (5874/7163), 10.08 MiB | 1Receiving objects:  83% (5946/7163), 10.08 MiB | 1error: RPC failed; curl 56 OpenSSL SSL_read: Software caused connection abort, errno 103
error: 5765 bytes of body are still expected
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
$

**Comment by deivid-rodriguez** [comment]
@mosab3482 Please stop opening issues that just copy-pasted output from a terminal without saying anything else. We consider this behaviour not acceptable, if you want to get help, make some effort on your side too.
