### ISSUE TITLE
Move away from TravisCI

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/bundler-site#548]
This repo still uses TravisCI. We should move away from it.

**Comment by olleolleolle** [comment]
https://twitter.com/james_hilliard/status/1336081776691843072 for a reason to do that.

**Comment by deivid-rodriguez** [comment]
Not sure whether the current deploy on master will succeed (seems currently broken). If it fails, that's a pretty strong reason to move away in addition to all others.

**Comment by deivid-rodriguez** [comment]
It seems fixed now, so never mind.

**Comment by deivid-rodriguez** [comment]
This was completed with #558.
