### ISSUE TITLE
Document error for how bundle manager $LOAD_PATH. 

### ISSUE THREAD

**Issue by zw963** [rubygems/bundler-site#577]
Following screenshot is come from  Bundler website for `groups`.  https://bundler.io/guides/groups.html

![image](https://user-images.githubusercontent.com/549126/120284924-5856fc00-c2ef-11eb-8c2d-ee7ba6ddedbb.png)

For above topic,  from my understood, that is say, only those gems in specified groups will add into ruby $LOAD_PATH, but,
obviously, this is not true, right? because i try it myself, and checked rubygems/rubygems#3683 too.

So, i guess we need fix this document for confusing.

Thank you.

**Comment by zw963** [comment]
In fact,  i am confusing about following doc screenshot too here:  https://bundler.io/man/gemfile.5.html

![image](https://user-images.githubusercontent.com/549126/120288559-f0a2b000-c2f2-11eb-89fd-1bd2c4152954.png)

since `Bundler.setup(:default)` will be always add all gems in all groups (e.g. development) into $LOAD_PATH , so, what is the 
difference of above several `bundle.setup` form ?

Let me guess, the only meaning of existence of this setup(*groups)  is only for `--without`, right?

**Comment by deivid-rodriguez** [comment]
I tried to rewrite documentation in #578 to clarify this.

Regarding your last question about the https://bundler.io/man/gemfile.5.html page, I think the difference is that `Bundler.setup(:default)` only sets up the `:default` group, namely, gems outside of any explicit groups, whereas `Bundler.setup` setups all non-optional groups.

**Comment by zw963** [comment]
Thank you for answer.

> I think the difference is that `Bundler.setup(:default)` only sets up the `:default` group, namely, gems outside of any explicit groups, whereas `Bundler.setup` setups all non-optional groups.

What is the means of `sets up the ??? group`?  as far as i know, `Bundler.setup` only add gems into $LOAD_PATH, but, if not use
--without option, `Bundler.setup(:default)` will add `foo` group gems into $LOAD_PATH, right? 

so, what is the difference of `setup(:default)` and `setup(:default, :foo)` ?

**Comment by deivid-rodriguez** [comment]
Yes, when I said "sets up the ??? group" I meant adding the gem to the `$LOAD_PATH`.

> so, what is the difference of setup(:default) and setup(:default, :foo) ?

The difference is that `Bundler.setup(:default)` only adds gems without explicit groups to the `$LOAD_PATH`, whereas `Bundler.setup(:default, :foo)` will add gems without explicit groups plus gems in the `:foo` group.

For example,

```ruby
source 'https://rubygems.org'
gem 'rake'
gem 'pry', group: 'foo'
```

```
$ ruby -rbundler -e 'Bundler.setup(:default); puts $LOAD_PATH'
/home/deivid/.rbenv/rbenv.d/exec/gem-rehash
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.19/lib
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/x86_64-linux
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/site_ruby
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/vendor_ruby/3.0.0
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/vendor_ruby/3.0.0/x86_64-linux
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/vendor_ruby
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/3.0.0
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/3.0.0/x86_64-linux
```

```
$ ruby -rbundler -e 'Bundler.setup(:default, :foo); puts $LOAD_PATH'
/home/deivid/.rbenv/rbenv.d/exec/gem-rehash
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/pry-0.14.1/lib
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/method_source-1.0.0/lib
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/coderay-1.1.3/lib
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/bundler-2.2.19/lib
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/rake-13.0.3/lib
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/site_ruby/3.0.0/x86_64-linux
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/site_ruby
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/vendor_ruby/3.0.0
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/vendor_ruby/3.0.0/x86_64-linux
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/vendor_ruby
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/3.0.0
/home/deivid/.rbenv/versions/3.0.1/lib/ruby/3.0.0/x86_64-linux
```

**Comment by zw963** [comment]
Oh, sorry for confusing, i can reproduce your's example, but when i test on my own a very simple non-rails project, it not works.

https://github.com/zw963/marketbet_crawler/blob/test_bundler/config/environment.rb

because i found the gems on :develpment always added into $LOAD_PATH, 

after research, i found the reason is:

Because i test $LOAD_PATH with pry.

after i start up pry, and `require_relative 'config/environment'`,  it seem like eager load all gems in Gemfile

![image](https://user-images.githubusercontent.com/549126/120304637-8abe2480-c302-11eb-94b9-74f641a1d13f.png)

Do you consider if this is a bug of pry?

**Comment by deivid-rodriguez** [comment]
I have no idea, sorry. I guess something is calling `Bundler.setup` without arguments before your call in `config/environment.rb`, so your call is being ignored. This is what I'm trying to clarify in #578, that only the first call to `Bundler.setup` is effective.
