### ISSUE TITLE
The 'with' option documentation should explain that it only applies to optional groups

### ISSUE THREAD

**Issue by izenk** [rubygems/bundler-site#597]
### Describe the problem as clearly as you can

```
bundle --version
Bundler version 2.3.0
```

```
bundle config
Settings are listed in order of priority. The top value will be used.
app_config
Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"

jobs
Set for your local app (/usr/local/bundle/config): 3

path
Set for the current user (/home/app/.bundle/config): "vendor/bundle"

silence_root_warning
Set via BUNDLE_SILENCE_ROOT_WARNING: true

with
Set for your local app (/usr/local/bundle/config): [:production]
Set for the current user (/home/app/.bundle/config): [:production]
```

'bundle install' - installs all gems from Gemfile from all groups, ignoring 'with' setting.
If I set 'without' setting, e.g.
```
bundle config without development test
```
and then run bundle install - only gems from production group will be installed as expected

**Comment by deivid-rodriguez** [comment]
I moved this to our documentation repository but then I noticed that sources for these documentation actually live at the upstream repository, ouch!

Anyways, can you reword these documentation to point this out? It's here: https://github.com/rubygems/rubygems/blob/dac8c02b37ff077aa66ba0e218058146d02dfea5/bundler/lib/bundler/man/bundle-config.1.ronn.
