### ISSUE TITLE
Document removing local override

### ISSUE THREAD

**Issue by shreyansh-g24** [rubygems/bundler-site#600]
Document - https://bundler.io/v1.3/git.html#local
File - https://github.com/rubygems/bundler-site/blob/master/source/v1.3/git.html.haml
Command - `bundle config --delete local.GEM_NAME`
Ref - https://github.com/rubygems/bundler/issues/2124

**Comment by tnir** [comment]
First of all, `https://bundler.io/v1.3/git.html#local` was migrated to `https://bundler.io/guides/git.html#local` in #651.

@shreyansh-g24 If you just want to see the reference, you can see it in Bundler 1.17 command references: https://bundler.io/v1.17/man/bundle-config.1.html. Or do you want to document the deprecation in the latest reference https://bundler.io/v2.3/man/bundle-config.1.html?

**Comment by shreyansh-g24** [comment]
The issue is already resolved within the links that you provided. The issue was to document the command in the references. Thank you.

**Comment by tnir** [comment]
Thanks for the confirmation.
