### ISSUE TITLE
Create a blog post to announce MFA policy changes

### ISSUE THREAD

**Issue by bettymakes** [rubygems/bundler-site#608]
Contributes to [MFA RFC](https://github.com/rubygems/rfcs/pull/36/files#diff-3d5cc3acc06fe7e9150fdbfc43399c5ad42572c122187774bfc3a4857df524f1R46-R67)

We will write a blog post to announce the new MFA policy changes. The initial announcement will outline [Phase 2's](https://github.com/rubygems/rfcs/pull/36/files#diff-3d5cc3acc06fe7e9150fdbfc43399c5ad42572c122187774bfc3a4857df524f1R46-R67) plan – recommending MFA for Top-100 Rubygems package maintainers.

As part of the communications effort, @sonalkr132 [has also recommended](https://bundler.slack.com/archives/C0HJMKWH4/p1648654978626329?thread_ts=1648491986.485729&cid=C0HJMKWH4) that we share the announcement through other channels.

### 📝 To Do's
- [ ] Write blog post
- [ ] Publish blog post
- [ ] Share post on `Ruby Weekly`
- [ ] Share post on `reddit` (e.g. `r/ruby`)

**Comment by sonalkr132** [comment]
https://github.com/rubygems/rubygems.github.io would be more suitable place for such blog post. bundler-site blog is not as active these days and is mostly reserved for bundler specific things.

**Comment by bettymakes** [comment]
Thanks for the pointer @sonalkr132! I had originally tried to open an issue over in [rubygems/rubygems.github.io](https://github.com/rubygems/rubygems.github.io), but wasn't able to do so. 

In the UI, the `issues` tab is missing. When I tried to navigate directly to the issues path (i.e. `https://github.com/rubygems/rubygems.github.io/issues`), I'm redirected to the pull request index view.

I ended up finding my way here thinking this was the perhaps the more appropriate place.
However, given your feedback, it's clearly not 😅. 

Happy to close the issue in this repo. Do you have alternative recommendations on where I could open this issue instead since I'm unable to on `rubygems/rubygems.github.io`?

**Comment by deivid-rodriguez** [comment]
I guess we can either enable issues at [rubygems/rubygems.github.io](https://github.com/rubygems/rubygems.github.io)?

**Comment by bettymakes** [comment]
I lack the context to know why `issues` weren't enabled on that repo. But, now we have a case for enabling it 😊 ? 
Would you be able to assist me with that @deivid-rodriguez?

**Comment by deivid-rodriguez** [comment]
I lack the context too 🤷. I think we have a case too, so if no one remembers that, I'd go for it :)

**Comment by indirect** [comment]
I think originally there was no blog there and we wanted to avoid docs issues that should be inside the main repo. I've turned on issues. 👍🏻

**Comment by bettymakes** [comment]
This issue has now been migrated into a more appropriate repo. Closing this since in favour of the [new issue](https://github.com/rubygems/rubygems.github.io/issues/109) 🎉 .

Thanks everyone for all your help!
