### ISSUE TITLE
/man/.* should be redirected to /v2.3/man/.*

### ISSUE THREAD

**Issue by tnir** [rubygems/bundler-site#618]
https://bundler.io/man/bundle-install.1.html is now the man for `bundle install` on Bundler 2.3 as of writing, but with release of 2.4, the content of `/man/bundle-install.1.html` will be updated.

I think `/man/bundle-install.1.html` should be redirect to `/v2.3/man/bundle-install.1.html` (if the current version is v2.3).

**Comment by gustavothecoder** [comment]
Can I work on this issue?

**Comment by deivid-rodriguez** [comment]
Yes, please!

**Comment by deivid-rodriguez** [comment]
Closed by #965.

**Comment by tnir** [comment]
Reopened by #990

**Comment by tnir** [comment]
Closing in favor of #992 while we tried it in #965, which was reverted in #990. Note that #992 would be resolved sooner in #993.
