### ISSUE TITLE
Align the design in Whats new with Bootstrap buttons

### ISSUE THREAD

**Issue by tnir** [rubygems/bundler-site#645]
`btn-secondary` (Bootstrap 4; BS4) is certainly the replacement of `btn-default` (BS3), but the appearance changes. 🤔 

cf. https://getbootstrap.com/docs/4.0/migration/#buttons

So, the color can be swapped at this time like:
```suggestion
      = link_to v, "/#{v}/whats_new.html", class: "btn btn-sm #{current_visible_version == v ? 'btn-primary' : 'btn-secondary'}"
```

_Originally posted by @tnir in https://github.com/rubygems/bundler-site/pull/644#discussion_r914929984_

**Comment by gustavothecoder** [comment]
This adjustment is still necessary? The current what's new page looks different from https://github.com/rubygems/bundler-site/pull/644#issuecomment-1181673691.

**Comment by tnir** [comment]
Thanks @gustavothecoder for reminding. This was dissolved in #873 removing the code and so you did not have to take care about this problem 🙇
