### ISSUE TITLE
Content too wide after bootstrap 5 upgrade

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/bundler-site#697]
I noticed a visual regression after this PR. The content is too wide and the margins too narrow, it looks worse the wider the screen is I believe. I reproduced in both Safari and Firefox.

#### Before

<img width="1440" alt="Captura de Pantalla 2022-07-16 a las 15 15 04" src="https://user-images.githubusercontent.com/2887858/179356477-b4681214-2fe1-4e1b-ae1e-4c2668f8d0d8.png">

#### After

<img width="1435" alt="Captura de Pantalla 2022-07-16 a las 15 15 40" src="https://user-images.githubusercontent.com/2887858/179356502-08c4bd08-f237-4ec2-8fc1-2905c90058eb.png">

_Originally posted by @deivid-rodriguez in https://github.com/rubygems/bundler-site/issues/681#issuecomment-1186182871_

**Comment by tnir** [comment]
> The content is too wide [...]

This is why Bootstrap 5 introduced another `xxl` (1400px) breakpoint for a larger screens (FHD, WQHD, 4K, 5K etc... is now common):

> New breakpoint! Added new xxl breakpoint for 1400px and up. No changes to all other breakpoints.
> -- https://getbootstrap.com/docs/5.2/migration/#grid-updates

> [...] the margins too narrow, [...]

Which margin do you mean? One under the line `Jan 23, 2022 Bundler v2.3: Locking the version of Bundler itself`?

**Comment by deivid-rodriguez** [comment]
The right and left margins around the main content.

#### Before
<img width="1419" alt="Captura de Pantalla 2022-07-16 a las 17 24 44" src="https://user-images.githubusercontent.com/2887858/179361318-2bc896ff-44d4-4ccd-8d51-0078839903fe.png">

#### After

<img width="1432" alt="Captura de Pantalla 2022-07-16 a las 17 25 29" src="https://user-images.githubusercontent.com/2887858/179361323-bfec7730-4456-4ead-a593-eb3f366c034f.png">

**Comment by tnir** [comment]
@deivid-rodriguez I hope this was fixed. Open an issue if you find something wrong.

**Comment by deivid-rodriguez** [comment]
Thank you!!
