### ISSUE TITLE
Attach Admin role to @tnir

### ISSUE THREAD

**Issue by tnir** [rubygems/bundler-site#730]
Any of `@rubygems` Org members/owners, or Repo Admins, could you add Admin role to @tnir in this repository to **configure custom domain for GitHub Pages in this repo** (which is different from [changing publishing source](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)) in #591?

- #591

### Resources
- https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site
   - > People with admin permissions for a repository can configure a custom domain for a GitHub Pages site.
- https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site
   - > People with admin or maintainer permissions for a repository can configure a publishing source for a GitHub Pages site.

cf.
- ~~#706~~

**Comment by tnir** [comment]
@deivid-rodriguez @olleolleolle @hsbt Can anyone do this?

**Comment by hsbt** [comment]
In my understanding, The migration of DocSearch is not acceptable now. 

We should wait for the final decision.

**Comment by tnir** [comment]
I meant #591 requires the permission, not #706.

**Comment by hsbt** [comment]
@tnir Can you clairfy why need admin role for `bundler-site` and `bundler.github.io` migration?

I know admin role easily work migration task, But It's role can delete and transfer repo. I'm being cautious.

**Comment by tnir** [comment]
The first comment of the issue was not fully updated.
Make sense to me. Enabling Pages requires more permission than Write. Maintain role might be enough in this case if I read it correctly and https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site is correct.

**Comment by hsbt** [comment]
Thanks for your explanation. I promote you to `maintain` role on `bundler-site` and `bundler.github.io` repos 🚀

**Comment by tnir** [comment]
@hsbt Thanks for apply maintain role to me in https://github.com/rubygems/bundler.github.io and https://github.com/rubygems/bundler-site, but it unveiled I need permissions to complete the task.

Task list on #591 was just updated, take a look at that 🙏

**Comment by hsbt** [comment]
I changed you to admin role at `bundler.github.io`. Is it right?

**Comment by tnir** [comment]
Thanks, but I need admin role in both `bundler.github.io` and this repo.

**Comment by hsbt** [comment]
fmm, Can you provide the instructions need by admin role?

**Comment by tnir** [comment]
@hsbt Replied in https://github.com/rubygems/bundler-site/issues/591#issuecomment-1198141229

**Comment by hsbt** [comment]
Thanks, got it. I'll comment #591 .
