### ISSUE TITLE
Use Custom GitHub Actions Workflows (beta) for GitHub Pages

### ISSUE THREAD

**Issue by tnir** [rubygems/bundler-site#790]
With [the release of Custom GitHub Actions Workflows (beta) for GitHub Pages](https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/) on July 27, 2022, we can benefit from it to make the publishing source from `gh-pages` branch to `main` especially after #789.

**Comment by hsbt** [comment]
I prefer to switch this. 

FYI: The current github pages already support to deploy same branch with root or any directory. We can choose this change before beta feature.

**Comment by indirect** [comment]
@hsbt I think we need to use GitHub Actions to run `middleman build`. So just choosing "deploy gh-pages branch to main branch" is not enough, and we need either a "normal" GitHub action or the beta for Pages.

**Comment by tnir** [comment]
Yes, https://github.com/actions/deploy-pages exists for a while, which can be used for your own Actions for Pages, and my understanding is @indirect' comment above. Custom GitHub Actions workflows (beta) for GitHub Pages (as of https://github.com/actions/deploy-pages/pull/42) does not include the Middleman workflow, so we need to write some code.

**Comment by tnir** [comment]
Even including `CNAME` file did not help me use the custom domain (#796) as follows, and I needed to restore the publishing source from `master` to `gh-pages` even after #795/#796.

- Workflow from gh-pages branch got `"page_url":"https://bundler.io/"`: https://github.com/rubygems/bundler-site/runs/7573442939?check_suite_focus=true
- but one from master branch got `"page_url":"https://blog.rubygems.org/bundler-site/"`: https://github.com/rubygems/bundler-site/runs/7573407610?check_suite_focus=true

@hsbt Can you check what happens and if CNAME is preserved as `bundler.io` when you change the source from `gh-pages` to `master` at https://github.com/rubygems/bundler-site/settings/pages?

**Comment by hsbt** [comment]
Custom domain configuration may depends on [this](https://github.com/rubygems/bundler-site/pull/795#issuecomment-1198918726).

**Comment by tnir** [comment]
Thanks. While it seems https://github.com/rubygems/bundler-site/settings/pages shows incorrect information to "Maintain" members, it will be no problem unless a "Maintain" member updates it. Closing.
