### ISSUE TITLE
Remove bundler-site-staging environment from GitHub Environment

### ISSUE THREAD

**Issue by tnir** [rubygems/bundler-site#800]
> [...] the latter [Stop deploying to GitHub Pages and use Heroku instead] seems slightly more desirable to me, because we currently have a permanently red Heroku staging pipeline [...]

by @deivid-rodriguez in https://github.com/rubygems/bundler-site/issues/591#issue-1077542574

## Motivation
#789 and #794 resolved a separation of the repos between source and artifacts and #795 and #796 released artifact logs from the Git repository. `bundler-site-staging` environment hosted on Heroku does not work for half a year and bothers visitors/contributors on the repo top (see below).

![github com_rubygems_bundler-site](https://user-images.githubusercontent.com/10229505/181704776-3f331329-99e6-4794-bd27-1efc2cad6c0b.png)

## TODO
- [x] Remove bundler-site-staging environment from [GitHub environments](https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#about-environments) via [GitHub environments API](https://docs.github.com/en/rest/deployments/environments#delete-an-environment)
- [x] Check it out again at https://github.com/rubygems/bundler-site/deployments/activity_log?environment=bundler-site-staging

**Comment by tnir** [comment]
@deivid-rodriguez What do you think about this strategy? If you agree, I can do it (I guess Maintain role is enough to comple this).

**Comment by deivid-rodriguez** [comment]
Yes, let's do it!

**Comment by deivid-rodriguez** [comment]
But wait,, I think review apps require at least one environment. I think that's why we have this "broken" bundler-site-staging. So I think if we do this we lose review apps.

**Comment by tnir** [comment]
Umm... I see. Even if we remove `bundler-site-staging` manually, Heroku Review Apps (New) re-create one? Actually I have never used Heroku's Review Apps **(New)** by myself (I needed to build our own Review Apps using Heroku without GitHub integration last year 😁 ) 😀 

But as https://blog.heroku.com/heroku-review-apps-ga shows, staging and review apps are in different columns, so the staging seems removable...?

**Comment by deivid-rodriguez** [comment]
I think review apps need to be part of a pipeline (all three columns), i.e., review apps need to be able to be promoted to a "real app", they cannot exist by themselves. At least this is the recollection I have from when we tried to remove staging in the past.

**Comment by indirect** [comment]
Yes, I believe that is correct. Review apps can only exist if staging still exists, although we can stop all staging resources.

**Comment by deivid-rodriguez** [comment]
I found the docs: https://devcenter.heroku.com/articles/pipelines#do-pipelines-always-require-a-app

By the way, review apps in other PRs are giving me 404 right now... 🤔.

**Comment by tnir** [comment]
Oh, I did not mean we should remove the stage named as `staging` from Heroku itself. I just meant why not manually removing [the environment named as `bundler-site-staging` by Heroku pipeline](https://github.com/rubygems/bundler-site/deployments/activity_log?environment=bundler-site-staging) from GitHub environments in the repo.

**Comment by deivid-rodriguez** [comment]
I deleted it!

**Comment by tnir** [comment]
Thank you. I will check if review apps still work with another PR.

**Comment by tnir** [comment]
Now we can close this 🚀  as we do not see any old obsolete logs either in the section on the repo top or on the repo deployments.

In the section on the repo top https://github.com/rubygems/bundler-site:

![github com_rubygems_bundler-site](https://user-images.githubusercontent.com/10229505/185868989-965103b7-8b7e-454d-b7ce-6dc4aee11460.png)

On the repo deployments https://github.com/rubygems/bundler-site/deployments#activity-log:

![github com_rubygems_bundler-site-deployments](https://user-images.githubusercontent.com/10229505/185869073-f23e2c15-caef-41df-bbf9-0f07e6e91fc1.png)

**Comment by indirect** [comment]
Nice work!
