### ISSUE TITLE
Replace ronn with pandoc

### ISSUE THREAD

**Issue by tnir** [rubygems/bundler-site#829]
The urrent `.ronn` files in https://github.com/rubygems/rubygems/tree/master/bundler/lib/bundler/man are almost (common) Markdown while its extension is `ronn`, and so we might be able to use [pandoc](https://pandoc.org/) to do the same thing with less additional effort.

For example, `ronn` parses `h1` markup incorrectly, so we need some workaround for it. [ronn](https://github.com/rtomayko/ronn) has not been maintained for 9 years.

## cf.
- #823

**Comment by indirect** [comment]
Ronn is at least written in ruby, while pandoc is 1) huge and 2) pandoc filters add python as a build dependency, which will greatly increase future maintenance burden. I would strongly prefer fixing the bug in ronn rather than adding the entire python ecosystem into this repo.

**Comment by simi** [comment]
Btw. there is https://github.com/apjanke/ronn-ng, we can try migrate in there and help maintain that one if needed.

**Comment by tnir** [comment]
`ronn-ng` gem, mentioned by @deivid-rodriguez before, also looks unmaintained any more to me.

**Comment by simi** [comment]
@tnir we can help with maintenance. Is there anything particular to address for now?

**Comment by tnir** [comment]
> As an alternative, you might want to check out [pandoc](http://johnmacfarlane.net/pandoc/) which can also convert markdown into roff manual pages.

Ronn-NG also recommends using pandoc.

@simi take a look at #823

**Comment by simi** [comment]
> > As an alternative, you might want to check out [pandoc](http://johnmacfarlane.net/pandoc/) which can also convert markdown into roff manual pages.
> 
> Ronn-NG also recommends using pandoc.

:thinking: It doesn't, it just mentions it as an alternative, which is just copy paste from original ronn repository README.

**Comment by deivid-rodriguez** [comment]
Should we close this issue? I think everyone agrees to stick with a Ruby based library. Good old `ronn` has served us well for more than 10 years without a single upstream patch, this doesn't look like a domain that changes very often and needs a lot of maintenance.

**Comment by tnir** [comment]
I think we do not have to do this in this repo in favor of #996.
