### ISSUE TITLE
Heroku’s Next Chapter (2022) affects our review apps?

### ISSUE THREAD

**Issue by tnir** [rubygems/bundler-site#872]
https://blog.heroku.com/next-chapter

cf. #800

**Comment by deivid-rodriguez** [comment]
I don't know, I hope not!

**Comment by tnir** [comment]
So, you mean we are in Free plan?

**Comment by hsbt** [comment]
The original post didn't say about review app. I'm not sure free usage includes review app with this Heroku changes.

**Comment by tnir** [comment]
(New) Review Apps, currently used in this project, require free Dynos. We will not be able to use Heroku RA when free dynos are no more available.

**Comment by tnir** [comment]
(We can use their open source support if we **are** in Free)

**Comment by simi** [comment]
:information_source: @hsbt offered transfer to Ruby OSS account if needed.

**Comment by tnir** [comment]
We see failures in Heroku review apps in #1000 and #1002 etc.. Does any maintainers of @rubygems dig into this?

**Comment by deivid-rodriguez** [comment]
No, so basically we need to upgrade our account to get review apps stable again, is that correct?

**Comment by hsbt** [comment]
I can prepare it under the ruby organization.

**Comment by indirect** [comment]
I am not sure what is going on, exactly, since some Review Apps are working without any problem, like this one from #1066 https://bundler-site-pr-templat-tiztnn.herokuapp.com

**Comment by indirect** [comment]
On #929, the error message was `Revision 80f9122a88c770a11726df4cd459c8b8acc7c166 does not exist in the repository https://github.com/tnir/middleman.git.`.

On #978 and #1065, both deployed successfully when I tried just now.

I have invited @tnir and @hsbt to the Heroku Pipeline, so hopefully you will be able to see any problems in the future. 👍🏻

**Comment by hsbt** [comment]
Thanks, I'll investigate them.

**Comment by olleolleolle** [comment]
Now, October 2023, are we using any Heroku Review apps? Are we on Netlify for the "review apps" now? (Can this Issue be closed?)

**Comment by simi** [comment]
Heroku is not used anymore.
