### ISSUE TITLE
/man/.* should be redirected to /v2.4/man/.*

### ISSUE THREAD

**Issue by tnir** [rubygems/bundler-site#992]
https://bundler.io/man/bundle-install.1.html is now the man for `bundle install` on Bundler 2.4 as of writing, but with release of 2.5 (or 3.0), the content of `/man/bundle-install.1.html` will be updated.

I think `/man/bundle-install.1.html` should be redirect to `/v2.4/man/bundle-install.1.html` (if the current version is v2.4).

**Comment by gustavothecoder** [comment]
@tnir @deivid-rodriguez looks like the error only occurs in production, I couldn't reproduce the error locally or in test environments ([example](https://bundler-site-use-ronn-n-2iqopp.herokuapp.com/)).

You guys have any info that can help me?

**Comment by deivid-rodriguez** [comment]
Can you access the review app at https://github.com/rubygems/bundler-site/pull/993? Does it look good? I guess if this is not reproducible on a review app, we can merge it directly and see how it goes (if it looks good to you).

**Comment by gustavothecoder** [comment]
> Can you access the review app at #993? Does it look good? I guess if this is not reproducible on a review app, we can merge it directly and see how it goes (if it looks good to you).

Yeah, looks good. I couldn't reproduce there either.

**Comment by tnir** [comment]
Reopening as #993 does not help address this.
